server:
  port: 8007
spring:
  application:
    name: consumer
    #Zipkin 是一款开源的分布式实时数据追踪系统
  zipkin:
    base-url: http://localhost:9411/
    #可以指定监控数据的采样率
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

feign:
  hystrix:
    enabled: false