server:
  port: 8030

spring:
  application:
    name: consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        #需要开启 hystrix.stream 端点的暴露,这样才能获取到监控信息 * 代表开启所有可能监控的端点
        include: "*"
