server:
  port: 8040
  #指定服务命名
spring:
  application:
    name: producer
  #指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

management:
  endpoints:
    web:
      exposure:
        #需要开启 hystrix.stream 端点的暴露,这样才能获取到监控信息 * 代表开启所有可能监控的端点
        include: "*"