server:
  port: 8071

spring:
  application:
    name: product1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000 #设置连接超时，默认是2秒
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
