server:
  port: 8070

spring:
  application:
    name: product1
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000 #设置连接超时，默认是2秒
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        #需要开启 hystrix.stream 端点的暴露,这样才能获取到监控信息 * 代表开启所有可能监控的端点
        include: "*"