server:
  port: 8008

spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
feign:
  hystrix:
    enabled: true
turbine:
  aggregator:
    cluster-config: default
  combine-host-port: true
  app-config: consumer,producer
  cluster-name-expression: "'default'"
